version: "0.0"

services:
  app:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    container_name: ml_app
    volumes:
      - ./src:/workspace/src        # main
      - ./notebooks:/workspace/notebooks
      - ./data:/workspace/data 
    ports:
      - "8888:8888"                 # Jupyter, API
    # depends_on:
    #   - mlflow
    networks:
      - ml_net
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    tty: true
    stdin_open: true

  # mlflow:
  #   build:
  #     context: ./mlflow
  #     dockerfile: ../docker/mlflow.Dockerfile
  #   container_name: mlflow
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./mlflow/mlruns:/mlflow/mlruns
  #   networks:
  #     - ml_net

  # airflow:
  #   build:
  #     context: ./airflow
  #     dockerfile: ../docker/airflow.Dockerfile
  #   container_name: airflow
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./airflow/dags:/opt/airflow/dags
  #     - ./airflow/logs:/opt/airflow/logs
  #   networks:
  #     - ml_net
  #   environment:
  #     - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
  #     - AIRFLOW__CORE__LOAD_EXAMPLES=False

networks:
  ml_net:
    driver: bridge
